table Customer
	lineageTag: 02afd36f-0b89-411d-866a-5c826f53f32f

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 32f52f28-b676-4fec-85b9-b82e09cd8c83
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 5b0ab19a-d713-48a1-8086-dae45d1ff3c2
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 8c784614-ff43-4c0c-affe-d6c7f13065af
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NerellaManojKumar\Downloads\OrderDetails_Data\OrderDetails_Data\Customer.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerID", Int64.Type}, {"CustomerName", type text}, {"Segment", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

