table Region
	lineageTag: 8838d893-7ca0-4547-a3d9-97429100e05d

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: dc7d1283-6417-46cd-b81d-dafc111c31eb
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: 70699477-0d97-4e55-8e40-c9f46cdbff05
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NerellaManojKumar\Downloads\OrderDetails_Data\OrderDetails_Data\Region.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"RegionID", Int64.Type}, {"RegionName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

