table SalesRep
	lineageTag: f97f2abf-0beb-440c-a68e-3209486d2757

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: 4274a529-35a7-4aff-b371-2cab0500aea9
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column SalesRepName
		dataType: string
		lineageTag: 41d235d9-7313-49ee-8cbc-262183702908
		summarizeBy: none
		sourceColumn: SalesRepName

		annotation SummarizationSetBy = Automatic

	partition SalesRep = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NerellaManojKumar\Downloads\OrderDetails_Data\OrderDetails_Data\SalesRep.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesRepID", Int64.Type}, {"SalesRepName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

