table SalesRep
	lineageTag: a57974e2-7dfe-43bf-a8a8-37e598700ba0

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: 37c15261-bdb8-4f5c-8a69-a8e9043677c6
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column SalesRepName
		dataType: string
		lineageTag: 42098931-d320-4864-a489-e742bb33007f
		summarizeBy: none
		sourceColumn: SalesRepName

		annotation SummarizationSetBy = Automatic

	partition SalesRep = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\PadavalaSai\Downloads\OrderDetails_Data\OrderDetails_Data\SalesRep.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesRepID", Int64.Type}, {"SalesRepName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

